// SPDX-License-Identifier: GPL-2.0-or-later
// Canonical names from the pinned Chocolate Doom d_englsh.h.
extension WAD {
    private static let mapNames: [String:String] = [
        "E1M1": "Hangar",
        "E1M2": "Nuclear Plant",
        "E1M3": "Toxin Refinery",
        "E1M4": "Command Control",
        "E1M5": "Phobos Lab",
        "E1M6": "Central Processing",
        "E1M7": "Computer Station",
        "E1M8": "Phobos Anomaly",
        "E1M9": "Military Base",
        "E2M1": "Deimos Anomaly",
        "E2M2": "Containment Area",
        "E2M3": "Refinery",
        "E2M4": "Deimos Lab",
        "E2M5": "Command Center",
        "E2M6": "Halls of the Damned",
        "E2M7": "Spawning Vats",
        "E2M8": "Tower of Babel",
        "E2M9": "Fortress of Mystery",
        "E3M1": "Hell Keep",
        "E3M2": "Slough of Despair",
        "E3M3": "Pandemonium",
        "E3M4": "House of Pain",
        "E3M5": "Unholy Cathedral",
        "E3M6": "Mt. Erebus",
        "E3M7": "Limbo",
        "E3M8": "Dis",
        "E3M9": "Warrens",
        "E4M1": "Hell Beneath",
        "E4M2": "Perfect Hatred",
        "E4M3": "Sever The Wicked",
        "E4M4": "Unruly Evil",
        "E4M5": "They Will Repent",
        "E4M6": "Against Thee Wickedly",
        "E4M7": "And Hell Followed",
        "E4M8": "Unto The Cruel",
        "E4M9": "Fear",
        "MAP01": "Entryway",
        "MAP02": "Underhalls",
        "MAP03": "The Gantlet",
        "MAP04": "The Focus",
        "MAP05": "The Waste Tunnels",
        "MAP06": "The Crusher",
        "MAP07": "Dead Simple",
        "MAP08": "Tricks And Traps",
        "MAP09": "The Pit",
        "MAP10": "Refueling Base",
        "MAP11": "'O' Of Destruction!",
        "MAP12": "The Factory",
        "MAP13": "Downtown",
        "MAP14": "The Inmost Dens",
        "MAP15": "Industrial Zone",
        "MAP16": "Suburbs",
        "MAP17": "Tenements",
        "MAP18": "The Courtyard",
        "MAP19": "The Citadel",
        "MAP20": "Gotcha!",
        "MAP21": "Nirvana",
        "MAP22": "The Catacombs",
        "MAP23": "Barrels O' Fun",
        "MAP24": "The Chasm",
        "MAP25": "Bloodfalls",
        "MAP26": "The Abandoned Mines",
        "MAP27": "Monster Condo",
        "MAP28": "The Spirit World",
        "MAP29": "The Living End",
        "MAP30": "Icon Of Sin",
        "MAP31": "Wolfenstein",
        "MAP32": "Grosse",
    ]
    func mapTitle(_ map: String) -> String {
        guard let title = Self.mapNames[map] else { return map }
        return "\(map): \(title)"
    }
}
