// SPDX-License-Identifier: GPL-2.0-or-later
// Typed action allowlists derived from the pinned Woof p_action.h.
#include "ActionSafety.h"
#include "p_action.h"
#include "i_system.h"
static const actionf_p1 actor_actions[] = {
    A_BFGSpray,
    A_Explode,
    A_Pain,
    A_PlayerScream,
    A_Fall,
    A_XScream,
    A_Look,
    A_Chase,
    A_FaceTarget,
    A_PosAttack,
    A_Scream,
    A_SPosAttack,
    A_VileChase,
    A_VileStart,
    A_VileTarget,
    A_VileAttack,
    A_StartFire,
    A_Fire,
    A_FireCrackle,
    A_Tracer,
    A_SkelWhoosh,
    A_SkelFist,
    A_SkelMissile,
    A_FatRaise,
    A_FatAttack1,
    A_FatAttack2,
    A_FatAttack3,
    A_BossDeath,
    A_CPosAttack,
    A_CPosRefire,
    A_TroopAttack,
    A_SargAttack,
    A_HeadAttack,
    A_BruisAttack,
    A_SkullAttack,
    A_Metal,
    A_SpidRefire,
    A_BabyMetal,
    A_BspiAttack,
    A_Hoof,
    A_CyberAttack,
    A_PainAttack,
    A_PainDie,
    A_KeenDie,
    A_BrainPain,
    A_BrainScream,
    A_BrainDie,
    A_BrainAwake,
    A_BrainSpit,
    A_SpawnSound,
    A_SpawnFly,
    A_BrainExplode,
    A_Detonate,
    A_Mushroom,
    A_Die,
    A_Spawn,
    A_Turn,
    A_Face,
    A_Scratch,
    A_PlaySound,
    A_RandomJump,
    A_LineEffect,
    A_BetaSkullAttack,
    A_Stop,
    A_SpawnObject,
    A_MonsterProjectile,
    A_MonsterBulletAttack,
    A_MonsterMeleeAttack,
    A_RadiusDamage,
    A_NoiseAlert,
    A_HealChase,
    A_SeekTracer,
    A_FindTracer,
    A_ClearTracer,
    A_JumpIfHealthBelow,
    A_JumpIfTargetInSight,
    A_JumpIfTargetCloser,
    A_JumpIfTracerInSight,
    A_JumpIfTracerCloser,
    A_JumpIfFlagsSet,
    A_AddFlags,
    A_RemoveFlags
};
static const actionf_p2 weapon_actions[] = {
    A_Light0,
    A_WeaponReady,
    A_Lower,
    A_Raise,
    A_Punch,
    A_ReFire,
    A_FirePistol,
    A_Light1,
    A_FireShotgun,
    A_Light2,
    A_FireShotgun2,
    A_CheckReload,
    A_OpenShotgun2,
    A_LoadShotgun2,
    A_CloseShotgun2,
    A_FireCGun,
    A_GunFlash,
    A_FireMissile,
    A_Saw,
    A_FirePlasma,
    A_BFGsound,
    A_FireBFG,
    A_FireOldBFG,
    A_WeaponProjectile,
    A_WeaponBulletAttack,
    A_WeaponMeleeAttack,
    A_WeaponSound,
    A_WeaponAlert,
    A_WeaponJump,
    A_ConsumeAmmo,
    A_CheckAmmo,
    A_RefireTo,
    A_GunFlashTo
};
void ME_RunActorAction(actionf_t action, struct mobj_s *actor)
{
    if (!action.p1) return;
    for (unsigned i = 0; i < sizeof(actor_actions)/sizeof(*actor_actions); i++)
        if (action.p1 == actor_actions[i]) { action.p1(actor); return; }
    I_Error("Action signature mismatch: weapon callback in actor state");
}
void ME_RunWeaponAction(actionf_t action, struct player_s *player, struct pspdef_s *weapon)
{
    if (!action.p2) return;
    for (unsigned i = 0; i < sizeof(weapon_actions)/sizeof(*weapon_actions); i++)
        if (action.p2 == weapon_actions[i]) { action.p2(player, weapon); return; }
    I_Error("Action signature mismatch: actor callback in weapon state");
}
